### ISSUE TITLE
MFC API リファレンス > MFC マクロとグローバル > 例外処理 ページの記載に不自然な点が散見される

### ISSUE THREAD

**Issue by beru** [MicrosoftDocs/cpp-docs.ja-jp#141]
MFC API リファレンス > MFC マクロとグローバル > [例外処理ページ](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/mfc/reference/exception-processing.md) の記載に問題を見つけました（[バージョン指定付きリンク](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md)）。

[AfxThrowDBException の Remarks](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md#remarks-16) に空の `「」` という記述が存在します。

[AfxThrowDBException の パラメーター](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md#%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E3%83%BC-10) の `pdb` の説明文章の途中に `CDatabase` という用語が不自然に挿入されています。

[CATCH_ALL の Remarks](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md#remarks-2) に閉じ括弧 `」` が単独で記述されています。

[AfxThrowDaoException の Remarks](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md#remarks-15) の記述が色々と壊れてます。

[AfxAbort の Remarks](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/8b723670fbb71dd31d2f73c7438c7d72408ed688/docs/mfc/reference/exception-processing.md#remarks-17) の説明文の途中に不自然に `AfxAbort` という用語が挿入されています。

機械翻訳さんもう少しなんとかなりませんか…。

**Comment by srvbpigh** [comment]
Hello, @beru
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@beru
 フィードバックをお送りいただきありがとうございました。問題のページは機械翻訳されており、常に完全に理解可能であるとは限りません。最近、右側に "英語で読む" オプションが追加されました。このオプションを使用すると、言語設定を変更しなくても英語バージョンに切り替えることができます。 
 敬具 
Microsoft DOCS International Team
