### ISSUE TITLE
数字の前後の半角空白について

### ISSUE THREAD

**Issue by beru** [MicrosoftDocs/cpp-docs.ja-jp#145]
質問させて下さい。

いつも日常で目にする文章とは違って、全体的に数字の前後に半角空白が入っている記述が多い気がします。可読性を上げる等の理由があって意図的にそうしてるのでしょうか？

**Comment by srvbpigh** [comment]
Hello, @beru
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@beru 様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by beru** [comment]
@CeciAc さん Let me refer the example sentence from [this page](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/styleguide/voice-tone.md#小学-5-年生の読解レベルを対象にする).

In English:
> Target a 5th Grade Reading Level

日本語
> 小学 5 年生の読解レベルを対象にする

I don't think Japanese people usually put extra white spaces around every numbers when they write.
So I thought the sentence should be written like this.
> 小学5年生の読解レベルを対象にする

**Comment by beru** [comment]
Standard writing styles may differ from language to language.
It could be just my speculation but if your stance is like `Why should I bother?`, then no wonder why there's such a mess around cpp-docs.ja-jp... :disappointed:

**Comment by beru** [comment]
うーん…「英語で嫁」って言われそうな気配がする…。

**Comment by CeciAc** [comment]
Hello, @beru

Thank you for your feedback. The spaces are intentionally inserted according to Microsoft Style Guide for product localization. If you are interested in further information, please see "Symbols and spaces" section in the guide which is available at https://www.microsoft.com/ja-jp/language/StyleGuides. 

Kind regards,
Microsoft DOCS International Team

**Comment by beru** [comment]
Hi, @CeciAc 

Thank you for the clarification. I really appreciate it.
