### ISSUE TITLE
`_Bool`の長さ

### ISSUE THREAD

**Issue by udaken** [MicrosoftDocs/cpp-docs.ja-jp#170]
C99で追加された、`_Bool`の定義が知りたいです。
(C++との相互運用のため)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2a3252f3-2390-77d1-75ee-00ff08584173
* Version Independent ID: 53786641-f25d-638f-18d5-8c7e19712776
* Content: [データ型の範囲](https://docs.microsoft.com/ja-jp/cpp/cpp/data-type-ranges?view=vs-2019#feedback)
* Content Source: [docs/cpp/data-type-ranges.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/data-type-ranges.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @udaken
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@udaken
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/cpp-docs/issues/1676) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
