### ISSUE TITLE
楕円?

### ISSUE THREAD

**Issue by sszk** [MicrosoftDocs/cpp-docs.ja-jp#228]
楕円(ellipse)は関係ないと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 516af34c-0d41-3ee3-2df1-e7d68eb17325
* Version Independent ID: 05d065d1-8cd4-d2b4-cbcb-4a68df79123c
* Content: [楕円および可変値引数テンプレート](https://docs.microsoft.com/ja-jp/cpp/cpp/ellipses-and-variadic-templates?view=vs-2019#feedback)
* Content Source: [docs/cpp/ellipses-and-variadic-templates.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/ellipses-and-variadic-templates.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @sszk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@sszk 
レポートをありがとうございました。 この欠陥はスペルミスの単語によるものでした。 代わりに、「楕円」(ellipses) は「省略点」(ellipsis) であることが意図されていました。 ソースファイルで修正されました。
