### ISSUE TITLE
Does strtod or wcstod invoke invalid parameter handler when overflow or underflow occurs?

### ISSUE THREAD

**Issue by miimou** [MicrosoftDocs/cpp-docs.ja-jp#229]
In the section "Return Value", this document says that wcstod and strtod set errno to ERANGE if overflow or underflow occurs *and* the invalid parameter handler is invoked.
&gt; *wcstod* returns values analogously to *strtod*. For both functions, *errno* is set to *ERANGE* if overflow or underflow occurs and the invalid parameter handler is invoked, as described in Parameter Validation.
It implies overflow or underflow may invoke invalid parameter handler, and errno is set only when invalid parameter handler invoked.

But,
* strtod does not invoke invalid parameter handler for overflow or underflow (for cases I tested).
* when overflow or underflow occurs, errno is set to ERANGE whether the invalid parameter handler called or not.

And,
* strtod does call invalid parameter handler when pointer passed as strSource is NULL.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0656f7f5-94a4-e2cd-c0ff-7949a271dd45
* Version Independent ID: 7f8311a0-098a-d03e-d215-61c00c88966e
* Content: [strtod、_strtod_l、wcstod、_wcstod_l](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @miimou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2136](https://github.com/MicrosoftDocs/cpp-docs/issues/2136) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @miimou, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/2136. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
