### ISSUE TITLE
Option name corrupsed in the Japanese translation (和訳のオプション名がおかしい)

### ISSUE THREAD

**Issue by tats-u** [MicrosoftDocs/cpp-docs.ja-jp#230]
- `/8 (ソースと実行可能文字セットを UTF-8 に設定する)`  →  `/utf-8 (ソースと実行可能文字セットを UTF-8 に設定する)`
- `/-8オプションを使用すると、` → `/utf-8オプションを使用すると、`

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 95cef197-b80b-d567-7650-b6b5f8741766
* Version Independent ID: dc4b1099-c2aa-5a85-14c7-9456ba39233b
* Content: [/8 (ソースと実行可能文字セットを UTF-8 に設定する)](https://docs.microsoft.com/ja-jp/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2019#feedback)
* Content Source: [docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @tats-u
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@tats-u  様:  

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 

サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム

**Comment by JasonCard** [comment]
@corob-msft Thank you for updating the source, so '/uft-8' won't be over-localized!

@tats-u Thank you for your feedback. Source was updated to prevent the option name from being over-localized, so translation should be updated in 1-2 days.

**Comment by tats-u** [comment]
Thank you for suppressing translation of code blocks.
