### ISSUE TITLE
Please fix the japanese translation

### ISSUE THREAD

**Issue by admiswalker** [MicrosoftDocs/cpp-docs.ja-jp#231]
Please fix the japanese translation of "署名されていない __int8", "署名されていない __int16" and "署名されていない __int16" to "unsigned __int8", "unsigned __int16" and "unsigned __int16".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2a3252f3-2390-77d1-75ee-00ff08584173
* Version Independent ID: 53786641-f25d-638f-18d5-8c7e19712776
* Content: [データ型の範囲](https://docs.microsoft.com/ja-jp/cpp/cpp/data-type-ranges?view=vs-2019#feedback)
* Content Source: [docs/cpp/data-type-ranges.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/data-type-ranges.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @admiswalker
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @admiswalker 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @admiswalker 
Thank you for your feedback.
I've opened this GitHub Issue [#2201](https://github.com/MicrosoftDocs/cpp-docs/issues/2201) to prevent the over-localization of those terms.

Best regards,
Jason
