### ISSUE TITLE
CComAutoThreadModule::Unlockはどこへ行きましたか？

### ISSUE THREAD

**Issue by tk1818** [MicrosoftDocs/cpp-docs.ja-jp#237]
CComAutoThreadModule::Unlockはどこへ行きましたか？

https://docs.microsoft.com/ja-jp/cpp/atl/reference/ccomautothreadmodule-class?view=vs-2019#ccomautothreadmoduleunlock

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e4305226-f21a-22fa-680c-41a4f441c997
* Version Independent ID: f0c3f269-8b8c-1a69-9142-06c67939ee67
* Content: [ATL モジュール クラス](https://docs.microsoft.com/ja-jp/cpp/atl/atl-module-classes?view=vs-2019)
* Content Source: [docs/atl/atl-module-classes.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/atl/atl-module-classes.md)
* Product: **visual-cpp**
* Technology: **cpp-atl**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @tk1818,
The doc indicates that this class was replaced by the CAtlAutoThreadModule and CAtlModule derived classes. If you look at [CAtlModule](https://docs.microsoft.com/cpp/atl/reference/catlmodule-class?view=msvc-160), it has lock() and unlock()

Take a look at that class, and if you have questions about how to use it you might try our [Developer Community](https://aka.ms/vsfeedback/browsecpp)

#please-close
