### ISSUE TITLE
日本語版の語順がおかしい

### ISSUE THREAD

**Issue by waiterw** [MicrosoftDocs/cpp-docs.ja-jp#249]
以下のように、htmlのcodeタグで囲まれてる単語が日本語訳で本来あるべき位置から跳び出ている感じになっている。

>RAII の原則を簡単に導入できるように、C++ 標準ライブラリでは、、、およびの3種類のスマートポインターを提供して std::unique_ptr std::shared_ptr std::weak_ptr います。 スマートポインターは、所有しているメモリの割り当てと削除を処理します。 次の例は、の呼び出しでヒープに割り当てられた配列メンバーを持つクラスを示して make_unique() います。 との呼び出し new delete は、クラスによってカプセル化され unique_ptr ます。 オブジェクトが widget スコープ外に出ると、unique_ptr デストラクターが呼び出され、配列に割り当てられたメモリが解放されます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [C++ へようこそ - Modern C++](https://docs.microsoft.com/ja-jp/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JasonCard FYI.

It does look like the sentence should read:
RAII の原則を簡単に導入できるように、C++ 標準ライブラリでは、std::unique_ptr、std::shared_ptr、std::weak_ptr およびの3種類のスマートポインターを提供しています。

I'm also curious if there's a missing とbetween new and delete. 

This isn't the only place in the Japanese translation where I've noticed either links or inline code elements appear misplaced in the translated sentence.

**Comment by JasonCard** [comment]
@corob-msft Thank you for pointing out this feedback to me. Yes, this is a known issue in machine translation that we hope to have it addressed soon in the MT engine. In the meantime, we would have to live with these MT issues for machine translated content. However, I'm going to upgrade this article to human translation as it seems to highly visible and we received this feedback specifically for this article. It should be done by next week and will update when done. 

@waiterw フィードバックをありがとうございました。この問題につきましては機械翻訳エンジンでの改善を待っている状況です。それまでは機械翻訳されているページでは見られる問題なのですが、ご指摘して頂いたこのページにつきましては人間翻訳で対応いたします。来週中には終わる予定ですが、終わり次第ご連絡いたします。

**Comment by JasonCard** [comment]
@corob-msft This article is now human translated and issue is resolved.

@waiterw このページは翻訳者によって改善されました。また何かフィードバックがありましたらお知らせください。

**Comment by corob-msft** [comment]
@JasonCard よし！ ありがとうございました。
