### ISSUE TITLE
複雑な数値計算 ではなく 複素数演算 が正しい

### ISSUE THREAD

**Issue by Qs-F** [MicrosoftDocs/cpp-docs.ja-jp#250]
タイトルが「C の複雑な数値演算のサポート」となっていますが、Complexを「複雑な」と訳してしまっていて、これは複素数という訳のほうが正しいと思われます。

ドキュメント内も入り混じってしまっていているようです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 837f9388-5530-798a-5b6d-aaa1a5c0e285
* Version Independent ID: fc31aaec-0539-bfc5-7d24-de55eb1d4a4c
* Content: [C の複雑な数値演算のサポート](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/complex-math-support?view=vs-2019)
* Content Source: [docs/c-runtime-library/complex-math-support.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/complex-math-support.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi @Qs-F ,
I'm sorry, we are unable to address machine translation issues.
#please-close

**Comment by Qs-F** [comment]
OK, thanks!
