### ISSUE TITLE
en-US が ja-JP に翻訳されてしまい意味がおかしくなっている。

### ISSUE THREAD

**Issue by juner** [MicrosoftDocs/cpp-docs.ja-jp#260]
翻訳の結果、 en-US が ja-JP に翻訳されて 意味が誤ってしまっている。

正しくは翻訳前と同様の `en-US` にすべきです。

翻訳前(英語)
![image](https://user-images.githubusercontent.com/753914/103171780-35cd3c80-4892-11eb-814c-e873e1511bd4.png)
![image](https://user-images.githubusercontent.com/753914/103171782-42519500-4892-11eb-974b-68ded7afe2b3.png)

翻訳後(日本語)
![image](https://user-images.githubusercontent.com/753914/103171725-e424b200-4891-11eb-84c8-024eb4a6a1b1.png)
![image](https://user-images.githubusercontent.com/753914/103171747-01598080-4892-11eb-8e92-3fba23a00216.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a25b2062-1d8a-a709-dcaa-638f7a1ebc01
* Version Independent ID: d734a773-6beb-305b-96f7-dff303a99567
* Content: [Language Strings](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/language-strings?view=msvc-160)
* Content Source: [docs/c-runtime-library/language-strings.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/language-strings.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by juner** [comment]
こちらも同様の問題です。

翻訳前(英語)
![image](https://user-images.githubusercontent.com/753914/103172078-31a21e80-4894-11eb-8655-3a014e2ddfe1.png)
![image](https://user-images.githubusercontent.com/753914/103172085-3b2b8680-4894-11eb-8860-aa51728ade94.png)

翻訳後(日本語)
![image](https://user-images.githubusercontent.com/753914/103171998-990b9e80-4893-11eb-92d0-cc9a068fc1b5.png)
![image](https://user-images.githubusercontent.com/753914/103172007-ae80c880-4893-11eb-8fb4-b9361c362b72.png)



#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: af5082d0-cd6f-9c82-05dc-46c780475aae
* Version Independent ID: c129526e-5da7-cd20-cead-9be9b18e45c3
* Content: [国/地域別文字列](https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/country-region-strings?view=msvc-160)
* Content Source: [docs/c-runtime-library/country-region-strings.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/country-region-strings.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
Hi,
I can't read your comment (English-only speaker), but I think I understand the problem.
I've marked the language strings and locale name strings so that they won't be machine translated. The fix should be live by end of day 1/13/2021
Thank you for bringing this to our attention.

**Comment by juner** [comment]
@TylerMSFT Could you handle this matter as well? 
https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/260#issuecomment-751469166

**Comment by TylerMSFT** [comment]
Hi @juner , what other matter do you mean?

**Comment by juner** [comment]
@TylerMSFT 
[docs/c-runtime-library/language-strings.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/language-strings.md) has been addressed, but [docs/c-runtime-library/country-region-strings.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/c-runtime-library/country-region-strings.md) has a similar problem.

**Comment by TylerMSFT** [comment]
@juner, absolutely. I'll fix that today. Thank you for calling it out.

**Comment by TylerMSFT** [comment]
@juner , I fixed this.
It may not be live for a day or two. Thank you for making the docs better.
