### ISSUE TITLE
_bstr_tクラス日本語ドキュメントの翻訳修正提案です。

### ISSUE THREAD

**Issue by berryzplus** [MicrosoftDocs/cpp-docs.ja-jp#264]
## 概要
> A _bstr_t object encapsulates the BSTR data type. The class manages resource allocation and deallocation through function calls to SysAllocString and SysFreeString and other BSTR APIs when appropriate. The _bstr_t class uses reference counting to avoid excessive overhead.

_bstr_tオブジェクトは BSTR データ型をカプセル化します。クラスは、SysAllocString および SysFreeString などの BSTR api 呼び出しによってリソースの割り当てと解放を管理します。 _bstr_t クラスは、過剰なオーバーヘッドを避けるために参照カウントを使用します。

## 構築
訳語が「建設」となっていますが「構築」ないし「コンストラクション」が適切だと思います。

## 操作
「アタッチ」と「デタッチ」が翻訳されていますが、関数名なので原文のままとすべきです。

## 演算子
訳語「オペレーター」よりも「演算子」が適切だと思います。
加算代入演算子が「演算子 +=」となっていますが、現文のままとすべきです。
加算演算子が「演算子 +」となっていますが、現文のままとすべきです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 61026df2-6b87-5d05-c367-c72883d71c86
* Version Independent ID: 9172365d-d9a5-9e70-cc42-c0b5af634368
* Content: [_bstr_t クラス](https://docs.microsoft.com/ja-jp/cpp/cpp/bstr-t-class?view=msvc-160)
* Content Source: [docs/cpp/bstr-t-class.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/bstr-t-class.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@berryzplus 
Thanks, we appreciate your report about translation issues. I've tagged the document with styles that should prevent "Attach" and "Detach" and other function names from being localized. Unfortunately, I can't affect the way "construction" gets machine translated to "(building) construction". An update to the localized content should appear this month.

翻訳の問題についてのご報告に感謝いたします。 「アタッチ」や「デタッチ」などの関数名がローカライズされないようにするスタイルでドキュメントにタグを付けました。 残念ながら、「コンストラクション」が機械翻訳されて「建設」になる方法に影響を与えることはできません。。 ローカライズされたコンテンツの更新が今月表示されます。
