### ISSUE TITLE
Mistranslated symbolic names.

### ISSUE THREAD

**Issue by kekyo** [MicrosoftDocs/cpp-docs.ja-jp#59]
These symbolic names can't translate because cause syntax error at compile time if use translated names.

![image](https://user-images.githubusercontent.com/6181948/52261443-c46a0500-296c-11e9-909b-ba105f8c0a7e.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [定義済みマクロ](https://docs.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=vs-2017)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by kekyo** [comment]
The screen shot if part of problem. Please check another symbol names at this page.

**Comment by LisandroSu** [comment]
Hello, @kekyo 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles. They may take some time to be online.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
