### ISSUE TITLE
誤植を見付けました

### ISSUE THREAD

**Issue by berryzplus** [MicrosoftDocs/cpp-docs.ja-jp#90]
構文
誤）/Ob{0|12|3}|
正）/Ob{0|1|2|3}|

引数
誤）3 /O1と/O2の既定値。 インライン展開しないように明示的にマークされていない関数をコンパイラで拡張できるようにします。
正）2 /O1と/O2の既定値。 明示的にインライン禁止とマークされていない関数をインライン展開できるようにコンパイラに指示します。 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b8753fc2-5ab9-47ad-f52b-ae878986bc0f
* Version Independent ID: 47c6098b-17b4-a22d-b21a-8d8032b0df78
* Content: [/Ob (関数のインライン展開)](https://docs.microsoft.com/ja-jp/cpp/build/reference/ob-inline-function-expansion?view=vs-2019#feedback)
* Content Source: [docs/build/reference/ob-inline-function-expansion.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/build/reference/ob-inline-function-expansion.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @berryzplus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by beru** [comment]
「インライン化しないと明記されていない関数ならばコンパイラが展開出来るようにします。」というのはどうでしょうか？

あと `inline expansion` はインライン展開と訳される事が多いので、「拡張」より「展開」という単語を選択した方が良いと思います。

**Comment by beru** [comment]
コンパイラに展開する機会を与えます、の方が allow の訳としてより nuance が伝わるかも？翻訳難しい…。

**Comment by berryzplus** [comment]
普段はテキトーに行間を補って理解してるので、いざ翻訳するとなると結構難しいですね。

en-us): Allows the compiler to expand any function not explicitly marked for no inlining.
ja-jp): インライン展開しないとマークされていないすべての関数をインライン展開できるようにします。

参考「インライン展開しないとマークする方法」 https://docs.microsoft.com/ja-jp/cpp/cpp/noinline?view=vs-2019

**Comment by beru** [comment]
ラテン文字使ってる言語から分かち書きが禁止されたらsnake_caseとかCamelCaseが使われるようになるので、よりプログラミング言語っぽくなって良いですね。

**Comment by CeciAc** [comment]
こんにちは、@berryzplus

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/cpp/build/reference/ob-inline-function-expansion?view=vs-2019#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team

**Comment by beru** [comment]
@CeciAc 

![image](https://user-images.githubusercontent.com/1131125/63523212-ae044f00-c534-11e9-9cd4-6619988863c8.png)

**Comment by berryzplus** [comment]
To: @CeciAc 
翻訳の訂正をしていただいてありがとうございます。
気を悪くしないで欲しいのですが、当初指摘していた「日本語版の誤記」(issue本文を参照) が直ってないです :sob:
内容は https://github.com/MicrosoftDocs/cpp-docs.ja-jp/issues/90#issuecomment-523931106 で @beru さんが図示してくれてる通りです。

**Comment by CeciAc** [comment]
こんにちは、@berryzplus

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team
